apiVersion: v1
kind: Service
metadata:
  name: shares-gains-uk-tax-calculator
  labels:
    app: shares-gains-uk-tax-calculator
spec:
  type: ClusterIP
  selector:
    app: shares-gains-uk-tax-calculator
  ports:
    - name: http
      port: 80
      targetPort: http
